/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccessTokenResponse {
  accessRequestId?: string;
  active?: boolean;
  expiresAt?: string;
  id?: string;
  reportCollectionId?: string;
  tokenValue?: string;
}
