/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccessRequestResponse {
  adminComment?: string;
  createdDate?: string;
  email?: string;
  id?: string;
  message?: string;
  name?: string;
  reportCollectionId?: string;
  status?: 'PENDING' | 'ACCEPTED' | 'REJECTED';
}
