/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccessRequestUpdateDto {
  adminComment?: string;
  status?: 'PENDING' | 'ACCEPTED' | 'REJECTED';
}
