/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccessRequestDto {
  email: string;
  message?: string;
  name: string;
  reportCollectionId: string;
}
