/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminResponse {
  allowedDomains?: Array<string>;
  createdDate?: string;
  id?: string;
  lastModifiedDate?: string;
  reportCollectionIds?: Array<string>;
  username?: string;
}
