/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuditLogResponse {
  actionType?: 'CREATE' | 'UPDATE' | 'DELETE' | 'ACCESS' | 'REVOKE';
  createdDate?: string;
  details?: string;
  entityId?: string;
  entityName?: string;
  id?: string;
  performedBy?: string;
}
