/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationResponse {
  accessRequestId?: string;
  createdDate?: string;
  id?: string;
  message?: string;
  read?: boolean;
  reportCollectionName?: string;
}
