/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccessTokenResponse } from '../models/access-token-response';
export interface PageResponseAccessTokenResponse {
  content?: Array<AccessTokenResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
