/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AllowedDomainResponse } from './allowed-domain-response';
export interface PageResponseAllowedDomainResponse {
  content?: Array<AllowedDomainResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
