/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccessRequestResponse } from '../models/access-request-response';
export interface PageResponseAccessRequestResponse {
  content?: Array<AccessRequestResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
