/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReportCollectionResponse } from './report-collection-response';
export interface PageResponseReportCollectionResponse {
  content?: Array<ReportCollectionResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
