/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditLogResponse } from '../models/audit-log-response';
export interface PageResponseAuditLogResponse {
  content?: Array<AuditLogResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
