/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReportCollectionRequest {
  description?: string;
  isLocked: boolean;
  isPublished: boolean;
  name: string;
}
