/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReportResponse {
  createdDate?: string;
  filePath?: string;
  id?: string;
  name?: string;
  reportCollectionId?: string;
  sizeBytes?: number;
  type?: 'CSV' | 'XLS' | 'XLSX' | 'XLSM' | 'XLSB' | 'XLTX';
}
