/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReportCollectionResponse {
  adminId?: string;
  createdDate?: string;
  description?: string;
  id?: string;
  locked?: boolean;
  name?: string;
  published?: boolean;
  reportIds?: Array<string>;
}
