services:
  postgres:
    container_name: postgres-sql-rpl
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: replocker
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - rpl-net
    restart: unless-stopped
  keycloak:
    container_name: keycloak-rpl
    image: quay.io/keycloak/keycloak:26.1.3
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_HOSTNAME: localhost
      KEYCLOAK_HTTP_ENABLED: true
      KEYCLOAK_PROXY: edge
    networks:
      - rpl-net
    command:
      - "start-dev"

networks:
  rpl-net:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local