/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReportCollectionRequest } from '../../models/report-collection-request';
import { ReportCollectionResponse } from '../../models/report-collection-response';

export interface CreateCollection$Params {
      body: ReportCollectionRequest
}

export function createCollection(http: HttpClient, rootUrl: string, params: CreateCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportCollectionResponse>> {
  const rb = new RequestBuilder(rootUrl, createCollection.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReportCollectionResponse>;
    })
  );
}

createCollection.PATH = '/report-collections/my/create';
