/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccessRequestDto } from '../../models/access-request-dto';
import { AccessRequestResponse } from '../../models/access-request-response';

export interface CreateAccessRequest$Params {
  collectionId: string;
      body: AccessRequestDto
}

export function createAccessRequest(http: HttpClient, rootUrl: string, params: CreateAccessRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<AccessRequestResponse>> {
  const rb = new RequestBuilder(rootUrl, createAccessRequest.PATH, 'post');
  if (params) {
    rb.path('collectionId', params.collectionId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccessRequestResponse>;
    })
  );
}

createAccessRequest.PATH = '/report-collections/public/{collectionId}/request-access';
