/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DownloadReport$Params {
  collectionId: string;
  reportId: string;
  accessToken?: string;
}

export function downloadReport(http: HttpClient, rootUrl: string, params: DownloadReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
  const rb = new RequestBuilder(rootUrl, downloadReport.PATH, 'get');
  if (params) {
    rb.path('collectionId', params.collectionId, {});
    rb.path('reportId', params.reportId, {});
    rb.header('accessToken', params.accessToken, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Blob>;
    })
  );
}

downloadReport.PATH = '/report-collections/public/{collectionId}/reports/{reportId}/download';
