/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseAccessRequestResponse } from '../../models/page-response-access-request-response';

export interface GetAccessRequests$Params {
  collectionId: string;
  page?: number;
  size?: number;
}

export function getAccessRequests(http: HttpClient, rootUrl: string, params: GetAccessRequests$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseAccessRequestResponse>> {
  const rb = new RequestBuilder(rootUrl, getAccessRequests.PATH, 'get');
  if (params) {
    rb.path('collectionId', params.collectionId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseAccessRequestResponse>;
    })
  );
}

getAccessRequests.PATH = '/report-collections/my/{collectionId}/access-requests';
