/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReportCollectionResponse } from '../../models/report-collection-response';

export interface GetPublishedCollection$Params {
  collectionId: string;
  accessToken?: string;
}

export function getPublishedCollection(http: HttpClient, rootUrl: string, params: GetPublishedCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportCollectionResponse>> {
  const rb = new RequestBuilder(rootUrl, getPublishedCollection.PATH, 'get');
  if (params) {
    rb.path('collectionId', params.collectionId, {});
    rb.header('accessToken', params.accessToken, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReportCollectionResponse>;
    })
  );
}

getPublishedCollection.PATH = '/report-collections/public/{collectionId}';
