/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseReportResponse } from '../../models/page-response-report-response';

export interface GetReports$Params {
  collectionId: string;
  page?: number;
  size?: number;
  accessToken?: string;
}

export function getReports(http: HttpClient, rootUrl: string, params: GetReports$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseReportResponse>> {
  const rb = new RequestBuilder(rootUrl, getReports.PATH, 'get');
  if (params) {
    rb.path('collectionId', params.collectionId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.header('accessToken', params.accessToken, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseReportResponse>;
    })
  );
}

getReports.PATH = '/report-collections/public/{collectionId}/reports';
