/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReportRequest } from '../../models/report-request';
import { ReportResponse } from '../../models/report-response';

export interface UpdateReport$Params {
  collectionId: string;
  reportId: string;
      body?: {
'request': ReportRequest;
'file'?: Blob;
}
}

export function updateReport(http: HttpClient, rootUrl: string, params: UpdateReport$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportResponse>> {
  const rb = new RequestBuilder(rootUrl, updateReport.PATH, 'put');
  if (params) {
    rb.path('collectionId', params.collectionId, {});
    rb.path('reportId', params.reportId, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReportResponse>;
    })
  );
}

updateReport.PATH = '/report-collections/my/{collectionId}/reports/{reportId}';
