/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccessRequestResponse } from '../../models/access-request-response';

export interface GetRequestDetails$Params {
  requestId: string;
}

export function getRequestDetails(http: HttpClient, rootUrl: string, params: GetRequestDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<AccessRequestResponse>> {
  const rb = new RequestBuilder(rootUrl, getRequestDetails.PATH, 'get');
  if (params) {
    rb.path('requestId', params.requestId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccessRequestResponse>;
    })
  );
}

getRequestDetails.PATH = '/access-requests/{requestId}';
