/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AccessRequestResponse } from '../models/access-request-response';
import { getRequestDetails } from '../fn/access-request-controller/get-request-details';
import { GetRequestDetails$Params } from '../fn/access-request-controller/get-request-details';
import { processRequest } from '../fn/access-request-controller/process-request';
import { ProcessRequest$Params } from '../fn/access-request-controller/process-request';

@Injectable({ providedIn: 'root' })
export class AccessRequestControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getRequestDetails()` */
  static readonly GetRequestDetailsPath = '/access-requests/{requestId}';

  /**
   * Get access request details.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRequestDetails()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRequestDetails$Response(params: GetRequestDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<AccessRequestResponse>> {
    return getRequestDetails(this.http, this.rootUrl, params, context);
  }

  /**
   * Get access request details.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRequestDetails$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRequestDetails(params: GetRequestDetails$Params, context?: HttpContext): Observable<AccessRequestResponse> {
    return this.getRequestDetails$Response(params, context).pipe(
      map((r: StrictHttpResponse<AccessRequestResponse>): AccessRequestResponse => r.body)
    );
  }

  /** Path part for operation `processRequest()` */
  static readonly ProcessRequestPath = '/access-requests/{requestId}';

  /**
   * Process access request.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `processRequest()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  processRequest$Response(params: ProcessRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<AccessRequestResponse>> {
    return processRequest(this.http, this.rootUrl, params, context);
  }

  /**
   * Process access request.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `processRequest$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  processRequest(params: ProcessRequest$Params, context?: HttpContext): Observable<AccessRequestResponse> {
    return this.processRequest$Response(params, context).pipe(
      map((r: StrictHttpResponse<AccessRequestResponse>): AccessRequestResponse => r.body)
    );
  }

}
