/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addDomain } from '../fn/admin-controller/add-domain';
import { AddDomain$Params } from '../fn/admin-controller/add-domain';
import { AdminResponse } from '../models/admin-response';
import { AllowedDomainResponse } from '../models/allowed-domain-response';
import { deleteDomain } from '../fn/admin-controller/delete-domain';
import { DeleteDomain$Params } from '../fn/admin-controller/delete-domain';
import { filterNotifications } from '../fn/admin-controller/filter-notifications';
import { FilterNotifications$Params } from '../fn/admin-controller/filter-notifications';
import { getCurrentAdmin } from '../fn/admin-controller/get-current-admin';
import { GetCurrentAdmin$Params } from '../fn/admin-controller/get-current-admin';
import { getDomains } from '../fn/admin-controller/get-domains';
import { GetDomains$Params } from '../fn/admin-controller/get-domains';
import { getLogs } from '../fn/admin-controller/get-logs';
import { GetLogs$Params } from '../fn/admin-controller/get-logs';
import { getUnreadNotifications } from '../fn/admin-controller/get-unread-notifications';
import { GetUnreadNotifications$Params } from '../fn/admin-controller/get-unread-notifications';
import { PageResponseAllowedDomainResponse } from '../models/page-response-allowed-domain-response';
import { PageResponseAuditLogResponse } from '../models/page-response-audit-log-response';
import { PageResponseNotificationResponse } from '../models/page-response-notification-response';

@Injectable({ providedIn: 'root' })
export class AdminControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getDomains()` */
  static readonly GetDomainsPath = '/admins/me/allowed-domain';

  /**
   * List allowed domains.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDomains()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDomains$Response(params?: GetDomains$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseAllowedDomainResponse>> {
    return getDomains(this.http, this.rootUrl, params, context);
  }

  /**
   * List allowed domains.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDomains$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDomains(params?: GetDomains$Params, context?: HttpContext): Observable<PageResponseAllowedDomainResponse> {
    return this.getDomains$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseAllowedDomainResponse>): PageResponseAllowedDomainResponse => r.body)
    );
  }

  /** Path part for operation `addDomain()` */
  static readonly AddDomainPath = '/admins/me/allowed-domain';

  /**
   * Add allowed domain.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addDomain()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addDomain$Response(params: AddDomain$Params, context?: HttpContext): Observable<StrictHttpResponse<AllowedDomainResponse>> {
    return addDomain(this.http, this.rootUrl, params, context);
  }

  /**
   * Add allowed domain.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addDomain$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addDomain(params: AddDomain$Params, context?: HttpContext): Observable<AllowedDomainResponse> {
    return this.addDomain$Response(params, context).pipe(
      map((r: StrictHttpResponse<AllowedDomainResponse>): AllowedDomainResponse => r.body)
    );
  }

  /** Path part for operation `getLogs()` */
  static readonly GetLogsPath = '/admins/my/audit-logs';

  /**
   * Get audit logs.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLogs()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLogs$Response(params?: GetLogs$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseAuditLogResponse>> {
    return getLogs(this.http, this.rootUrl, params, context);
  }

  /**
   * Get audit logs.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLogs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLogs(params?: GetLogs$Params, context?: HttpContext): Observable<PageResponseAuditLogResponse> {
    return this.getLogs$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseAuditLogResponse>): PageResponseAuditLogResponse => r.body)
    );
  }

  /** Path part for operation `getCurrentAdmin()` */
  static readonly GetCurrentAdminPath = '/admins/me';

  /**
   * Get current admin profile.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCurrentAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentAdmin$Response(params?: GetCurrentAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminResponse>> {
    return getCurrentAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * Get current admin profile.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCurrentAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentAdmin(params?: GetCurrentAdmin$Params, context?: HttpContext): Observable<AdminResponse> {
    return this.getCurrentAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<AdminResponse>): AdminResponse => r.body)
    );
  }

  /** Path part for operation `filterNotifications()` */
  static readonly FilterNotificationsPath = '/admins/me/notification';

  /**
   * Filter notifications.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filterNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  filterNotifications$Response(params?: FilterNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseNotificationResponse>> {
    return filterNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * Filter notifications.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filterNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  filterNotifications(params?: FilterNotifications$Params, context?: HttpContext): Observable<PageResponseNotificationResponse> {
    return this.filterNotifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseNotificationResponse>): PageResponseNotificationResponse => r.body)
    );
  }

  /** Path part for operation `getUnreadNotifications()` */
  static readonly GetUnreadNotificationsPath = '/admins/me/notification/unread';

  /**
   * Get unread notifications.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUnreadNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadNotifications$Response(params?: GetUnreadNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseNotificationResponse>> {
    return getUnreadNotifications(this.http, this.rootUrl, params, context);
  }

  /**
   * Get unread notifications.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUnreadNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnreadNotifications(params?: GetUnreadNotifications$Params, context?: HttpContext): Observable<PageResponseNotificationResponse> {
    return this.getUnreadNotifications$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseNotificationResponse>): PageResponseNotificationResponse => r.body)
    );
  }

  /** Path part for operation `deleteDomain()` */
  static readonly DeleteDomainPath = '/admins/me/allowed-domain/{id}';

  /**
   * Delete allowed domain.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteDomain()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteDomain$Response(params: DeleteDomain$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteDomain(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete allowed domain.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteDomain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteDomain(params: DeleteDomain$Params, context?: HttpContext): Observable<void> {
    return this.deleteDomain$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
