/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AccessRequestResponse } from '../models/access-request-response';
import { createAccessRequest } from '../fn/report-collection-controller/create-access-request';
import { CreateAccessRequest$Params } from '../fn/report-collection-controller/create-access-request';
import { createCollection } from '../fn/report-collection-controller/create-collection';
import { CreateCollection$Params } from '../fn/report-collection-controller/create-collection';
import { deleteCollection } from '../fn/report-collection-controller/delete-collection';
import { DeleteCollection$Params } from '../fn/report-collection-controller/delete-collection';
import { deleteReport } from '../fn/report-collection-controller/delete-report';
import { DeleteReport$Params } from '../fn/report-collection-controller/delete-report';
import { downloadReport } from '../fn/report-collection-controller/download-report';
import { DownloadReport$Params } from '../fn/report-collection-controller/download-report';
import { getAccessRequests } from '../fn/report-collection-controller/get-access-requests';
import { GetAccessRequests$Params } from '../fn/report-collection-controller/get-access-requests';
import { getAccessTokens } from '../fn/report-collection-controller/get-access-tokens';
import { GetAccessTokens$Params } from '../fn/report-collection-controller/get-access-tokens';
import { getCollectionDetails } from '../fn/report-collection-controller/get-collection-details';
import { GetCollectionDetails$Params } from '../fn/report-collection-controller/get-collection-details';
import { getMyCollections } from '../fn/report-collection-controller/get-my-collections';
import { GetMyCollections$Params } from '../fn/report-collection-controller/get-my-collections';
import { getPublishedCollection } from '../fn/report-collection-controller/get-published-collection';
import { GetPublishedCollection$Params } from '../fn/report-collection-controller/get-published-collection';
import { getPublishedCollections } from '../fn/report-collection-controller/get-published-collections';
import { GetPublishedCollections$Params } from '../fn/report-collection-controller/get-published-collections';
import { getReports } from '../fn/report-collection-controller/get-reports';
import { GetReports$Params } from '../fn/report-collection-controller/get-reports';
import { getReportsAsAdmin } from '../fn/report-collection-controller/get-reports-as-admin';
import { GetReportsAsAdmin$Params } from '../fn/report-collection-controller/get-reports-as-admin';
import { PageResponseAccessRequestResponse } from '../models/page-response-access-request-response';
import { PageResponseAccessTokenResponse } from '../models/page-response-access-token-response';
import { PageResponseReportCollectionResponse } from '../models/page-response-report-collection-response';
import { PageResponseReportResponse } from '../models/page-response-report-response';
import { ReportCollectionResponse } from '../models/report-collection-response';
import { ReportResponse } from '../models/report-response';
import { revokeAccessToken } from '../fn/report-collection-controller/revoke-access-token';
import { RevokeAccessToken$Params } from '../fn/report-collection-controller/revoke-access-token';
import { updateCollection } from '../fn/report-collection-controller/update-collection';
import { UpdateCollection$Params } from '../fn/report-collection-controller/update-collection';
import { updateReport } from '../fn/report-collection-controller/update-report';
import { UpdateReport$Params } from '../fn/report-collection-controller/update-report';
import { uploadReport } from '../fn/report-collection-controller/upload-report';
import { UploadReport$Params } from '../fn/report-collection-controller/upload-report';

@Injectable({ providedIn: 'root' })
export class ReportCollectionControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateReport()` */
  static readonly UpdateReportPath = '/report-collections/my/{collectionId}/reports/{reportId}';

  /**
   * Update report (RepLocker Admin).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateReport()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  updateReport$Response(params: UpdateReport$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportResponse>> {
    return updateReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Update report (RepLocker Admin).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateReport$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  updateReport(params: UpdateReport$Params, context?: HttpContext): Observable<ReportResponse> {
    return this.updateReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReportResponse>): ReportResponse => r.body)
    );
  }

  /** Path part for operation `createAccessRequest()` */
  static readonly CreateAccessRequestPath = '/report-collections/public/{collectionId}/request-access';

  /**
   * Submit access request for locked collection.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createAccessRequest()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAccessRequest$Response(params: CreateAccessRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<AccessRequestResponse>> {
    return createAccessRequest(this.http, this.rootUrl, params, context);
  }

  /**
   * Submit access request for locked collection.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createAccessRequest$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAccessRequest(params: CreateAccessRequest$Params, context?: HttpContext): Observable<AccessRequestResponse> {
    return this.createAccessRequest$Response(params, context).pipe(
      map((r: StrictHttpResponse<AccessRequestResponse>): AccessRequestResponse => r.body)
    );
  }

  /** Path part for operation `uploadReport()` */
  static readonly UploadReportPath = '/report-collections/my/{collectionId}/reports/upload-report';

  /**
   * Upload report to collection (RepLocker Admin).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadReport()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadReport$Response(params: UploadReport$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportResponse>> {
    return uploadReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Upload report to collection (RepLocker Admin).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadReport$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadReport(params: UploadReport$Params, context?: HttpContext): Observable<ReportResponse> {
    return this.uploadReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReportResponse>): ReportResponse => r.body)
    );
  }

  /** Path part for operation `createCollection()` */
  static readonly CreateCollectionPath = '/report-collections/my/create';

  /**
   * Create new report collection as RepLocker admin.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCollection()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCollection$Response(params: CreateCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportCollectionResponse>> {
    return createCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Create new report collection as RepLocker admin.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCollection$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCollection(params: CreateCollection$Params, context?: HttpContext): Observable<ReportCollectionResponse> {
    return this.createCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReportCollectionResponse>): ReportCollectionResponse => r.body)
    );
  }

  /** Path part for operation `updateCollection()` */
  static readonly UpdateCollectionPath = '/report-collections/my/{collectionId}/edit';

  /**
   * Update report collection metadata.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateCollection()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCollection$Response(params: UpdateCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportCollectionResponse>> {
    return updateCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Update report collection metadata.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateCollection$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCollection(params: UpdateCollection$Params, context?: HttpContext): Observable<ReportCollectionResponse> {
    return this.updateCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReportCollectionResponse>): ReportCollectionResponse => r.body)
    );
  }

  /** Path part for operation `getPublishedCollections()` */
  static readonly GetPublishedCollectionsPath = '/report-collections/public';

  /**
   * List report collections (public).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPublishedCollections()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPublishedCollections$Response(params?: GetPublishedCollections$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseReportCollectionResponse>> {
    return getPublishedCollections(this.http, this.rootUrl, params, context);
  }

  /**
   * List report collections (public).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPublishedCollections$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPublishedCollections(params?: GetPublishedCollections$Params, context?: HttpContext): Observable<PageResponseReportCollectionResponse> {
    return this.getPublishedCollections$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseReportCollectionResponse>): PageResponseReportCollectionResponse => r.body)
    );
  }

  /** Path part for operation `getPublishedCollection()` */
  static readonly GetPublishedCollectionPath = '/report-collections/public/{collectionId}';

  /**
   * Get report collection details (public).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPublishedCollection()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPublishedCollection$Response(params: GetPublishedCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportCollectionResponse>> {
    return getPublishedCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Get report collection details (public).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPublishedCollection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPublishedCollection(params: GetPublishedCollection$Params, context?: HttpContext): Observable<ReportCollectionResponse> {
    return this.getPublishedCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReportCollectionResponse>): ReportCollectionResponse => r.body)
    );
  }

  /** Path part for operation `getReports()` */
  static readonly GetReportsPath = '/report-collections/public/{collectionId}/reports';

  /**
   * Get reports in collection.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getReports()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReports$Response(params: GetReports$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseReportResponse>> {
    return getReports(this.http, this.rootUrl, params, context);
  }

  /**
   * Get reports in collection.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getReports$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReports(params: GetReports$Params, context?: HttpContext): Observable<PageResponseReportResponse> {
    return this.getReports$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseReportResponse>): PageResponseReportResponse => r.body)
    );
  }

  /** Path part for operation `downloadReport()` */
  static readonly DownloadReportPath = '/report-collections/public/{collectionId}/reports/{reportId}/download';

  /**
   * Download report file.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `downloadReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadReport$Response(params: DownloadReport$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return downloadReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Download report file.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `downloadReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  downloadReport(params: DownloadReport$Params, context?: HttpContext): Observable<Blob> {
    return this.downloadReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /** Path part for operation `getMyCollections()` */
  static readonly GetMyCollectionsPath = '/report-collections/my';

  /**
   * List report collections by RepLocker admin.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMyCollections()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyCollections$Response(params?: GetMyCollections$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseReportCollectionResponse>> {
    return getMyCollections(this.http, this.rootUrl, params, context);
  }

  /**
   * List report collections by RepLocker admin.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMyCollections$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyCollections(params?: GetMyCollections$Params, context?: HttpContext): Observable<PageResponseReportCollectionResponse> {
    return this.getMyCollections$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseReportCollectionResponse>): PageResponseReportCollectionResponse => r.body)
    );
  }

  /** Path part for operation `getCollectionDetails()` */
  static readonly GetCollectionDetailsPath = '/report-collections/my/{collectionId}';

  /**
   * Get collection details for RepLocker admin.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCollectionDetails()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCollectionDetails$Response(params: GetCollectionDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportCollectionResponse>> {
    return getCollectionDetails(this.http, this.rootUrl, params, context);
  }

  /**
   * Get collection details for RepLocker admin.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCollectionDetails$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCollectionDetails(params: GetCollectionDetails$Params, context?: HttpContext): Observable<ReportCollectionResponse> {
    return this.getCollectionDetails$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReportCollectionResponse>): ReportCollectionResponse => r.body)
    );
  }

  /** Path part for operation `getReportsAsAdmin()` */
  static readonly GetReportsAsAdminPath = '/report-collections/my/{collectionId}/reports';

  /**
   * Get reports in collection.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getReportsAsAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReportsAsAdmin$Response(params: GetReportsAsAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseReportResponse>> {
    return getReportsAsAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * Get reports in collection.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getReportsAsAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReportsAsAdmin(params: GetReportsAsAdmin$Params, context?: HttpContext): Observable<PageResponseReportResponse> {
    return this.getReportsAsAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseReportResponse>): PageResponseReportResponse => r.body)
    );
  }

  /** Path part for operation `getAccessTokens()` */
  static readonly GetAccessTokensPath = '/report-collections/my/{collectionId}/access-tokens';

  /**
   * List access tokens for locked report collection.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAccessTokens()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAccessTokens$Response(params: GetAccessTokens$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseAccessTokenResponse>> {
    return getAccessTokens(this.http, this.rootUrl, params, context);
  }

  /**
   * List access tokens for locked report collection.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAccessTokens$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAccessTokens(params: GetAccessTokens$Params, context?: HttpContext): Observable<PageResponseAccessTokenResponse> {
    return this.getAccessTokens$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseAccessTokenResponse>): PageResponseAccessTokenResponse => r.body)
    );
  }

  /** Path part for operation `getAccessRequests()` */
  static readonly GetAccessRequestsPath = '/report-collections/my/{collectionId}/access-requests';

  /**
   * List access request for locked report collection.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAccessRequests()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAccessRequests$Response(params: GetAccessRequests$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseAccessRequestResponse>> {
    return getAccessRequests(this.http, this.rootUrl, params, context);
  }

  /**
   * List access request for locked report collection.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAccessRequests$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAccessRequests(params: GetAccessRequests$Params, context?: HttpContext): Observable<PageResponseAccessRequestResponse> {
    return this.getAccessRequests$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseAccessRequestResponse>): PageResponseAccessRequestResponse => r.body)
    );
  }

  /** Path part for operation `deleteReport()` */
  static readonly DeleteReportPath = '/report-collections/my/{collectionId}/reports/{reportId}/delete';

  /**
   * Delete report (RepLocker Admin).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteReport()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteReport$Response(params: DeleteReport$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteReport(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete report (RepLocker Admin).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteReport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteReport(params: DeleteReport$Params, context?: HttpContext): Observable<void> {
    return this.deleteReport$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteCollection()` */
  static readonly DeleteCollectionPath = '/report-collections/my/{collectionId}/delete';

  /**
   * Delete report collection cascade.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCollection()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCollection$Response(params: DeleteCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete report collection cascade.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCollection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCollection(params: DeleteCollection$Params, context?: HttpContext): Observable<void> {
    return this.deleteCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `revokeAccessToken()` */
  static readonly RevokeAccessTokenPath = '/report-collections/my/{collectionId}/access-tokens/{tokenId}/revoke';

  /**
   * Revoke access token (RepLocker Admin).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `revokeAccessToken()` instead.
   *
   * This method doesn't expect any request body.
   */
  revokeAccessToken$Response(params: RevokeAccessToken$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return revokeAccessToken(this.http, this.rootUrl, params, context);
  }

  /**
   * Revoke access token (RepLocker Admin).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `revokeAccessToken$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  revokeAccessToken(params: RevokeAccessToken$Params, context?: HttpContext): Observable<void> {
    return this.revokeAccessToken$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
