/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AllowedDomainRequest } from '../../models/allowed-domain-request';
import { AllowedDomainResponse } from '../../models/allowed-domain-response';

export interface AddDomain$Params {
      body: AllowedDomainRequest
}

export function addDomain(http: HttpClient, rootUrl: string, params: AddDomain$Params, context?: HttpContext): Observable<StrictHttpResponse<AllowedDomainResponse>> {
  const rb = new RequestBuilder(rootUrl, addDomain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AllowedDomainResponse>;
    })
  );
}

addDomain.PATH = '/admins/me/allowed-domain';
