/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminResponse } from '../../models/admin-response';

export interface GetCurrentAdmin$Params {
}

export function getCurrentAdmin(http: HttpClient, rootUrl: string, params?: GetCurrentAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminResponse>> {
  const rb = new RequestBuilder(rootUrl, getCurrentAdmin.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminResponse>;
    })
  );
}

getCurrentAdmin.PATH = '/admins/me';
